# **Review Questions**


#### **1)	Define the following metrics and perform the following operations** 
    i)	Write a Python program using Python Lists 
    ii)	Write a Python program and NumPy
    Matrix A =  [[ 3.7827  3.3454  3.2341]  , [ 2.2122  3.5678  3.9087] , 
    [1.1234  2.8934,  5.9087]].

    Matrix B =  [[ 3.1234  3.0987  3.1234]  , [ 2.1111  3.2222  3.3333] , 
    [1.0987  1.3456,  5.1234]].

    Matrix C =  [[ 3.1243  3.0989  3.1256 ]  , [ 2.6721  3.6785  3.9017] , 
    [1.1254  2.8956,  5.9187]].


 


##### **i)	Write a Python program using Python Lists** 

In [6]:
# Define Matrix A using Python lists
matrix_a = [
    [3.7827, 3.3454, 3.2341],
    [2.2122, 3.5678, 3.9087],
    [1.1234, 2.8934, 5.9087]
]

# Define Matrix B using Python lists
matrix_b = [
    [3.1234, 3.0987, 3.1234],
    [2.1111, 3.2222, 3.3333],
    [1.0987, 1.3456, 5.1234]
]

# Define Matrix C using Python lists
matrix_c = [
    [3.1243, 3.0989, 3.1256],
    [2.6721, 3.6785, 3.9017],
    [1.1254, 2.8956, 5.9187]
]
print("The following are Matrices by using Python lists")
# Print the matrices
print("Matrix A:")
for row in matrix_a:
    print(row)

print("\nMatrix B:")
for row in matrix_b:
    print(row)

print("\nMatrix C:")
for row in matrix_c:
    print(row)


The following are Matrices by using Python lists
Matrix A:
[3.7827, 3.3454, 3.2341]
[2.2122, 3.5678, 3.9087]
[1.1234, 2.8934, 5.9087]

Matrix B:
[3.1234, 3.0987, 3.1234]
[2.1111, 3.2222, 3.3333]
[1.0987, 1.3456, 5.1234]

Matrix C:
[3.1243, 3.0989, 3.1256]
[2.6721, 3.6785, 3.9017]
[1.1254, 2.8956, 5.9187]


##### **ii)	Write a Python program and NumPy**

In [7]:
import numpy as np

# Define Matrix A using NumPy
matrix_a = np.array([
    [3.7827, 3.3454, 3.2341],
    [2.2122, 3.5678, 3.9087],
    [1.1234, 2.8934, 5.9087]
])

# Define Matrix B using NumPy
matrix_b = np.array([
    [3.1234, 3.0987, 3.1234],
    [2.1111, 3.2222, 3.3333],
    [1.0987, 1.3456, 5.1234]
])

# Define Matrix C using NumPy
matrix_c = np.array([
    [3.1243, 3.0989, 3.1256],
    [2.6721, 3.6785, 3.9017],
    [1.1254, 2.8956, 5.9187]
])

# Print the matrices
print("Matrix A:")
print(matrix_a)

print("\nMatrix B:")
print(matrix_b)

print("\nMatrix C:")
print(matrix_c)

# Example Operations:
# Adding Matrices A and B
matrix_sum = np.add(matrix_a, matrix_b)
print("\nMatrix A + Matrix B:")
print(matrix_sum)

# Subtracting Matrix C from Matrix A
matrix_difference = np.subtract(matrix_a, matrix_c)
print("\nMatrix A - Matrix C:")
print(matrix_difference)

# Multiplying Matrix A and Matrix B (element-wise)
matrix_product = np.multiply(matrix_a, matrix_b)
print("\nMatrix A * Matrix B (element-wise):")
print(matrix_product)

# Matrix Multiplication (dot product) of A and C
matrix_dot_product = np.dot(matrix_a, matrix_c)
print("\nMatrix A dot Matrix C:")
print(matrix_dot_product)


Matrix A:
[[3.7827 3.3454 3.2341]
 [2.2122 3.5678 3.9087]
 [1.1234 2.8934 5.9087]]

Matrix B:
[[3.1234 3.0987 3.1234]
 [2.1111 3.2222 3.3333]
 [1.0987 1.3456 5.1234]]

Matrix C:
[[3.1243 3.0989 3.1256]
 [2.6721 3.6785 3.9017]
 [1.1254 2.8956 5.9187]]

Matrix A + Matrix B:
[[ 6.9061  6.4441  6.3575]
 [ 4.3233  6.79    7.242 ]
 [ 2.2221  4.239  11.0321]]

Matrix A - Matrix C:
[[ 0.6584  0.2465  0.1085]
 [-0.4599 -0.1107  0.007 ]
 [-0.002  -0.0022 -0.01  ]]

Matrix A * Matrix B (element-wise):
[[11.81488518 10.36639098 10.10138794]
 [ 4.67017542 11.49616516 13.02886971]
 [ 1.23427958  3.89335904 30.27263358]]

Matrix A dot Matrix C:
[[24.39718909 33.39292289 44.01762197]
 [20.84394582 31.2975706  43.96936027]
 [17.89094374 31.23390788 49.77230051]]


#### **2)	Write a Python Program and perform the following operations ?**
I.	Create a List **{1225, 4986, 6789, 7890, 2345, 6783, 0987, 1234, 8765, 3456}**\
II.	Iterate using a for loop\
III.	Iterate using for loop and range\
IV.	List Comprehension\
V.	Enumerate\
VI.	Iter function and next function\
VII.	Map function\
VIII.	Using zip\
IX.	Using NumPy Module


In [8]:
# I. Creating a List
my_list = [1225, 4986, 6789, 7890, 2345, 6783, 987, 1234, 8765, 3456]

# II. Iterate Using a for Loop
print("I. The output is using for loop")
for item in my_list:
    print(item)
print("***************************************")
print()

# III. Iterate Using for Loop and range
print("II. The output is using for loop with range:")
for i in range(len(my_list)):
    print(my_list[i])
print("***************************************")
print()

print("III. List Comprehension")
# IV. List Comprehension
# Example: Create a new list with each item squared
squared_list = [item**2 for item in my_list]
print(squared_list)
print("***************************************")
print()

print("IV. Using Enumarate function ")
# V. Enumerate
for index, item in enumerate(my_list):
    print(f"Index: {index}, Value: {item}")
print("***************************************")
print()


# VI. iter Function and next Function
print("V. iter Function and next Function")
list_iterator = iter(my_list)
while True:
    try:
        item = next(list_iterator)
        print(item)
    except StopIteration:
        break
print("***************************************")
print()


# VII. map Function
print("VI. Map function")
def square(x):
    return x**2

squared_map = list(map(square, my_list))
print(squared_map)
print("***************************************")
print()

# VIII. Using zip
print("VII. using zip ")
# Create a second list for zipping
list2 = [i * 2 for i in my_list]

# Use zip to pair elements from both lists
for item1, item2 in zip(my_list, list2):
    print(f"Original: {item1}, Doubled: {item2}")
print("***************************************")
print()

# IX. Using NumPy Module
print("IX. Using Numpy module")
import numpy as np

# Convert the list to a NumPy array
numpy_array = np.array(my_list)

# Perform operations using NumPy
squared_array = np.square(numpy_array)
print(squared_array)

# Example of another mathematical operation using NumPy
mean_value = np.mean(numpy_array)
print(f"Mean Value: {mean_value}")
print("***************************************")
print()


I. The output is using for loop
1225
4986
6789
7890
2345
6783
987
1234
8765
3456
***************************************

II. The output is using for loop with range:
1225
4986
6789
7890
2345
6783
987
1234
8765
3456
***************************************

III. List Comprehension
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]
***************************************

IV. Using Enumarate function 
Index: 0, Value: 1225
Index: 1, Value: 4986
Index: 2, Value: 6789
Index: 3, Value: 7890
Index: 4, Value: 2345
Index: 5, Value: 6783
Index: 6, Value: 987
Index: 7, Value: 1234
Index: 8, Value: 8765
Index: 9, Value: 3456
***************************************

V. iter Function and next Function
1225
4986
6789
7890
2345
6783
987
1234
8765
3456
***************************************

VI. Map function
[1500625, 24860196, 46090521, 62252100, 5499025, 46009089, 974169, 1522756, 76825225, 11943936]
***************************************

VII. using zi

##### **3)	For a List A, B, C, D, E write a python program to compute all the combinations and permutations** 



In [11]:
import itertools

# Initialize the items
items = ['A', 'B', 'C', 'D', 'E']

# Function to display combinations
def display_combinations(elements):
    print("\nGenerating Combinations:")
    for length in range(1, len(elements) + 1):
        combs = list(itertools.combinations(elements, length))
        print(f"Combinations of length {length}: {combs}")

# Function to display permutations
def display_permutations(elements):
    print("\nGenerating Permutations:")
    for length in range(1, len(elements) + 1):
        perms = list(itertools.permutations(elements, length))
        print(f"Permutations of length {length}: {perms}")

# Execute the functions
display_combinations(items)
display_permutations(items)



Generating Combinations:
Combinations of length 1: [('A',), ('B',), ('C',), ('D',), ('E',)]
Combinations of length 2: [('A', 'B'), ('A', 'C'), ('A', 'D'), ('A', 'E'), ('B', 'C'), ('B', 'D'), ('B', 'E'), ('C', 'D'), ('C', 'E'), ('D', 'E')]
Combinations of length 3: [('A', 'B', 'C'), ('A', 'B', 'D'), ('A', 'B', 'E'), ('A', 'C', 'D'), ('A', 'C', 'E'), ('A', 'D', 'E'), ('B', 'C', 'D'), ('B', 'C', 'E'), ('B', 'D', 'E'), ('C', 'D', 'E')]
Combinations of length 4: [('A', 'B', 'C', 'D'), ('A', 'B', 'C', 'E'), ('A', 'B', 'D', 'E'), ('A', 'C', 'D', 'E'), ('B', 'C', 'D', 'E')]
Combinations of length 5: [('A', 'B', 'C', 'D', 'E')]

Generating Permutations:
Permutations of length 1: [('A',), ('B',), ('C',), ('D',), ('E',)]
Permutations of length 2: [('A', 'B'), ('A', 'C'), ('A', 'D'), ('A', 'E'), ('B', 'A'), ('B', 'C'), ('B', 'D'), ('B', 'E'), ('C', 'A'), ('C', 'B'), ('C', 'D'), ('C', 'E'), ('D', 'A'), ('D', 'B'), ('D', 'C'), ('D', 'E'), ('E', 'A'), ('E', 'B'), ('E', 'C'), ('E', 'D')]
Permutations

#### **4)	Using the same list use itertools compute permutations and combinations** 

In [10]:
import itertools

# Initialize the items
items = ['A', 'B', 'C', 'D', 'E']

# Function to display combinations
def display_combinations(elements):
    print("\nGenerating Combinations:")
    # Generate combinations of all possible lengths
    for length in range(1, len(elements) + 1):
        combs = list(itertools.combinations(elements, length))
        print(f"Combinations of length {length}:")
        for comb in combs:
            print(comb)

# Function to display permutations
def display_permutations(elements):
    print("\nGenerating Permutations:")
    # Generate permutations of all possible lengths
    for length in range(1, len(elements) + 1):
        perms = list(itertools.permutations(elements, length))
        print(f"Permutations of length {length}:")
        for perm in perms:
            print(perm)

# Execute the functions
display_combinations(items)
display_permutations(items)



Generating Combinations:
Combinations of length 1:
('A',)
('B',)
('C',)
('D',)
('E',)
Combinations of length 2:
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'D')
('C', 'E')
('D', 'E')
Combinations of length 3:
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
('A', 'C', 'D')
('A', 'C', 'E')
('A', 'D', 'E')
('B', 'C', 'D')
('B', 'C', 'E')
('B', 'D', 'E')
('C', 'D', 'E')
Combinations of length 4:
('A', 'B', 'C', 'D')
('A', 'B', 'C', 'E')
('A', 'B', 'D', 'E')
('A', 'C', 'D', 'E')
('B', 'C', 'D', 'E')
Combinations of length 5:
('A', 'B', 'C', 'D', 'E')

Generating Permutations:
Permutations of length 1:
('A',)
('B',)
('C',)
('D',)
('E',)
Permutations of length 2:
('A', 'B')
('A', 'C')
('A', 'D')
('A', 'E')
('B', 'A')
('B', 'C')
('B', 'D')
('B', 'E')
('C', 'A')
('C', 'B')
('C', 'D')
('C', 'E')
('D', 'A')
('D', 'B')
('D', 'C')
('D', 'E')
('E', 'A')
('E', 'B')
('E', 'C')
('E', 'D')
Permutations of length 3:
('A', 'B', 'C')
('A', 'B', 'D')
('A', 'B', 'E')
(